name: kiro

services:
    db:
        image: mysql:8.4.6
        env_file:
            - .env
        volumes:
            - kiro-db:/var/lib/mysql
        ports:
            - "7773:3306"
        command: ["--log_bin_trust_function_creators=1"]

    api:
        image: kiro-api
        build:
            context: ../api
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - db
        # ports:
        #     - "7772:8080"
        volumes:
            - kiro-api:/app/uploads

    app:
        image: kiro-app
        build:
            context: ../app
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - api
        ports:
            - "7771:7771"

    nginx:
        image: kiro-nginx
        ports:
            - "80:80"
        depends_on:
            - app
            - api

    phpmyadmin:
        image: phpmyadmin
        # restart: always
        ports:
            - 7774:80
        # volumes:
        #     - ./theme:/var/www/html/themes/testdee:ro
        environment:
            # - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_PORT=3306
        depends_on:
            - db

volumes:
    kiro-db:
    kiro-api: