name: kiro

services:
    db:
        image: mysql:8.4.6
        env_file:
            - .env
        volumes:
            - kiro-db:/var/lib/mysql
        ports:
            - "7778:3306"
        command: ["--log_bin_trust_function_creators=1"]

    api:
        image: kiro-image:latest
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - "5053:8080"
        volumes:
            - kiro-api:/app/upload

    phpmyadmin:
        image: phpmyadmin
        # restart: always
        ports:
            - 7774:80
        # volumes:
        #     - ./theme:/var/www/html/themes/testdee:ro
        environment:
            # - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_PORT=3306

volumes:
    kiro-db:
    kiro-api: